### ISSUE TITLE
Server name resets when editing an existing server

### ISSUE THREAD

**Issue by Felix14-v2** [Player005/BetterAddServer#2]
**Demo**

https://github.com/Player005/BetterAddServer/assets/75726196/1a574685-ed85-4578-ba8f-1b7172911612

**Expected behavior**
Server name field should be cleared only when clearing the IP address.

**Comment by Player005** [comment]
Thanks for the report, I'll look into this later today, should be an easy fix so expect a release soon!

**Comment by Player005** [comment]
Fixed!

**Comment by Clozent** [comment]
It doesn't seem to be fixed... Tried it on Fabric 1.20.6 and it still overrides the entered server name if you edit the address
