### ISSUE TITLE
[Suggestion] Remove "Play" From all Server Names

### ISSUE THREAD

**Issue by bruh1273** [Player005/BetterAddServer#5]
I believe that when adding a server, it should automatically remove the word "Play" from the start of the server name, because almost every server's IP starts with `play.`.

**Comment by Player005** [comment]
Sounds good, I personally never realised many servers still used that, (at least not the servers I play on :shrug:),
this has now been implemented on the 1.20.6 branch ([download build](https://github.com/Player005/BetterAddServer/actions/runs/9119200328/artifacts/1511101087)), will be backported and released on modrinth in the next few days.

**Comment by Player005** [comment]
Seems like I kinda forgot about this 😄
sorry, the update is now live on modrinth!
