### ISSUE TITLE
Server name is overridden when focusing on the address

### ISSUE THREAD

**Issue by Clozent** [Player005/BetterAddServer#6]
### Steps to reproduce[^1]:

1. Click on the "Add Server" button in Minecraft
2. Enter a server name
3. Enter a valid server address

### Result:
The server name you entered is overridden by the automatic server naming.

### Expected result
The server name you entered is not overridden by the automatic server naming, since you entered it's name manually.

### Additional details
The override seems to occur when focusing on the server address (making the cursor show up), and not just when changing it. This means that even after typing the server address and name to your liking, simply clicking on the address row will override the server name.

[^1]: Tested on Minecraft 1.20.6, Fabric Loader version 0.15.11

**Comment by Player005** [comment]
Honestly, I didn't think this was going to be an issue since I would expect people to enter the address first and then the name, however you are probably right and this should be fixed properly - looking into it now

**Comment by Player005** [comment]
Do you think it would be enough if the server name was only replaced when actually changing the address, or should the mod instead detect when the name was customised and stop changing it even when changing the address?

**Comment by Clozent** [comment]
I think the second option is preferable, where the mod detects that the server name was customized and stop changing it, even when changing the address.

**Comment by Player005** [comment]
Thanks, this was now implemented on the 1.20.6 branch, but I will need to test it some more before publishing the change to modrinth soon.

**Comment by Player005** [comment]
Done. Feel free to contact me if there are any bug or improvement ideas
