### ISSUE TITLE
Please revise your description

### ISSUE THREAD

**Issue by enigmafyv** [Player005/BetterAddServer#7]
In your description, specifically the sentence, "For example: When you enter an _IP address_ like hypixel.net, the mod automatically generates the server name (Hypixel) by omitting the domain ending (".net") and capitalising the first letter, instead of leaving the default name "Minecraft Server"," you need to correct your statement.  'hypixel.net' is not an IP address, it's a domain name.

**Comment by Player005** [comment]
I know it's not an IP, but most people don't know what a domain is and would understand 'IP' better than 'domain'.
Maybe something like "server address" would work, I think that's what it's called in-game too.
